name: npm vs snyk
on: push

env:
  BRANCH_NAME: '${{ github.event.inputs.branch_name || github.head_ref || github.ref_name  }}'
  NODE_VERSION: 16
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: NPM Audit
        run: npm audit

      - name: Install Snyk
        uses: snyk/actions/setup@master
        env:
          node-version: ${{ secrets.SNYK_TOKEN }}
          
      - name: snyk tests
        run: snyk test -d --print-deps






